#Generic Makefile for C projects which automatically keeps track of source file dependencies. Run `make depend' initially and whenever source files are added or removed. Unit tests are run with `make test' and each unit test source file should end with `$(test_suffix).c'.


#CONFIGURATION

progname = Test
test_suffix = Test
CFLAGS += -Wall
LDFLAGS = 
LDLIBS = -lgc -lm


#TEMPLATE

test_sources := $(wildcard *?$(test_suffix).c)
test_objects := $(patsubst %.c,%.o,$(test_sources))
test_binaries := $(patsubst %.c,%,$(test_sources))

prog_sources := $(filter-out $(test_sources),$(wildcard *.c))
prog_objects := $(patsubst %.c,%.o,$(prog_sources))

$(progname): $(prog_objects)


##Source file dependencies

depend: $(prog_sources) $(test_sources)
	makedepend -- $(CFLAGS) -- -Y $^ 2> /dev/null && rm Makefile.bak


##Unit testing

.PHONY: test
test: $(test_binaries)
	$(foreach test,$^,./$(test);)

%$(test_suffix): %$(test_suffix).o $(filter-out $(progname).o,$(prog_objects))
	$(CC) $(LDFLAGS) $^ $(LDLIBS) -o $@


##Cleanup

.PHONY: clean
clean:
	rm -f $(prog_objects) $(test_objects) $(test_binaries)


#RULES GENERATED BY MAKEDEPEND
# DO NOT DELETE

LineClipping.o: LineClipping.h
PersonTime.o: LineClipping.h PersonTime.h Util.h
LineClippingTest.o: LineClipping.h Util.h
Test.o: PersonTime.h Util.h
