#Generic Makefile for C projects which automatically keeps track of source file dependencies. Run `make depend' initially and whenever source files are added or removed. Unit tests are run with `make test' and each unit test source file should end with `_test.c'.


#CONFIGURATION

progname = Test
CFLAGS = -Wall
LDFLAGS = 
LDLIBS = -lm


#TEMPLATE

sources := $(wildcard *.c)
objects := $(patsubst %.c,%.o,$(sources))
test_objects := $(patsubst %.c,%.o,$(wildcard *_test.c))
prog_objects := $(filter-out $(test_objects),$(objects))

$(progname): $(prog_objects)


##Source file dependencies

depend: $(sources)
	makedepend -- $(CFLAGS) -- -Y $^ 2> /dev/null && rm Makefile.bak
	

##Unit testing

test_binaries := $(patsubst %.c,%,$(wildcard *_test.c))

.PHONY: test
test: $(test_binaries)
	$(foreach test,$^,./$(test))

%_test: %_test.o $(filter-out $(progname).o,$(prog_objects))
	$(CC) $(LDFLAGS) $^ $(LDLIBS) -o $@


##Cleanup

.PHONY: clean
clean:
	rm -f *.d *.o *_test


#RULES GENERATED BY MAKEDEPEND
# DO NOT DELETE

PersonTime.o: PersonTime.h Util.h
Test.o: PersonTime.h Util.h
